// Generated by Wrangler on Sun May 19 2024 17:07:22 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
  math_rock_stack_sessions: KVNamespace;
  CLOUDFLARE_ACCOUNT_ID: '887644ede3080f7152aa22e9ecf52f0f';
  SESSION_SECRET: string;
  DATABASE_NAME: string;
  DB: D1Database;
}
