// Generated by Wrangler on Sun May 12 2024 22:57:14 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
  CLOUDFLARE_ACCOUNT_ID: '887644ede3080f7152aa22e9ecf52f0f';
  SESSION_SECRET: string;
  DB: D1Database;
}
