// Generated by Wrangler on Fri May 17 2024 23:34:28 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
  CLOUDFLARE_ACCOUNT_ID: '887644ede3080f7152aa22e9ecf52f0f';
  SESSION_SECRET: string;
  DATABASE_NAME: string;
  DB: D1Database;
}
